# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: check-toml
    - id: check-symlinks
    - id: check-added-large-files
    - id: check-vcs-permalinks
    - id: debug-statements
    - id: trailing-whitespace
      exclude_types: ["image", "svg"]
    - id: end-of-file-fixer
    - id: mixed-line-ending

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 'v1.10.0'
  hooks:
    - id: python-check-blanket-noqa
    - id: python-check-blanket-type-ignore
    - id: python-use-type-annotations

- repo: https://github.com/asottile/yesqa
  rev: v1.5.0
  hooks:
  - id: yesqa

- repo: https://github.com/asottile/pyupgrade
  rev: 'v3.17.0'
  hooks:
    - id: pyupgrade
      args: ["--py38-plus"]

- repo: https://github.com/wimglenn/reorder-python-imports-black
  # See https://github.com/psf/black/issues/4175
  rev: v3.12.0
  hooks:
    - id: reorder-python-imports
      args: ["--py38-plus"]

- repo: https://github.com/PyCQA/flake8
  rev: '7.1.1'
  hooks:
    - id: flake8
      language_version: python3
      additional_dependencies:
      # NOTE: autoupdate does not pick up flake8-bugbear since it is a
      # transitive dependency. Make sure to update flake8-bugbear
      # manually on a regular basis.
      - flake8-bugbear==23.9.16

- repo: https://github.com/psf/black
  rev: '24.8.0'
  hooks:
    - id: black

- repo: https://github.com/pdm-project/pdm
  rev: '2.18.1'
  hooks:
    - id: pdm-lock-check
